/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campeonato;

/**
 *
 * @author Sergop
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpciones = new javax.swing.JMenu();
        Salir = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemReporteJugador = new javax.swing.JMenuItem();
        itemReporteEquipo = new javax.swing.JMenuItem();
        itemListadoEquipos = new javax.swing.JMenuItem();
        itemReporteIntegrantesEquipos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemTablaPosiciones = new javax.swing.JMenuItem();
        itemTablaGoleadores = new javax.swing.JMenuItem();
        itemTablaMenosVencida = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemResultadoEncuentro = new javax.swing.JMenuItem();
        itemEquipoPuntos = new javax.swing.JMenuItem();
        itemPromedioPuntos = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuOpciones.setText("Opciones");

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        menuOpciones.add(Salir);

        jMenuBar1.add(menuOpciones);
        menuOpciones.getAccessibleContext().setAccessibleDescription("");

        menuReportes.setText("Reportes");

        itemReporteJugador.setText("Jugador");
        itemReporteJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReporteJugadorActionPerformed(evt);
            }
        });
        menuReportes.add(itemReporteJugador);

        itemReporteEquipo.setText("Equipo");
        menuReportes.add(itemReporteEquipo);

        itemListadoEquipos.setText("Listado de equipos");
        menuReportes.add(itemListadoEquipos);

        itemReporteIntegrantesEquipos.setText("Integrantes de un equipo");
        menuReportes.add(itemReporteIntegrantesEquipos);
        menuReportes.add(jSeparator1);

        itemTablaPosiciones.setText("Tabla general de posiciones");
        menuReportes.add(itemTablaPosiciones);

        itemTablaGoleadores.setText("Tabla de goleadores");
        menuReportes.add(itemTablaGoleadores);

        itemTablaMenosVencida.setText("Tabla de valla menos vencida");
        menuReportes.add(itemTablaMenosVencida);
        menuReportes.add(jSeparator2);

        itemResultadoEncuentro.setText("Resultado de un encuentro");
        menuReportes.add(itemResultadoEncuentro);

        itemEquipoPuntos.setText("Equipo con más puntos");
        menuReportes.add(itemEquipoPuntos);

        itemPromedioPuntos.setText("Promedio de puntos por equipo");
        menuReportes.add(itemPromedioPuntos);

        jMenuBar1.add(menuReportes);

        menuAcercaDe.setText("Acerca de");
        jMenuBar1.add(menuAcercaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void itemReporteJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemReporteJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem itemEquipoPuntos;
    private javax.swing.JMenuItem itemListadoEquipos;
    private javax.swing.JMenuItem itemPromedioPuntos;
    private javax.swing.JMenuItem itemReporteEquipo;
    private javax.swing.JMenuItem itemReporteIntegrantesEquipos;
    private javax.swing.JMenuItem itemReporteJugador;
    private javax.swing.JMenuItem itemResultadoEncuentro;
    private javax.swing.JMenuItem itemTablaGoleadores;
    private javax.swing.JMenuItem itemTablaMenosVencida;
    private javax.swing.JMenuItem itemTablaPosiciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenu menuReportes;
    // End of variables declaration//GEN-END:variables
}
